### ISSUE TITLE
Heb12 Mobile on iOS (Sorta)

### ISSUE THREAD

**Issue by petabyt** [heb12/heb12-mobile#8]
Really just a handy shortcut to the page.

![Heb12iOS](https://user-images.githubusercontent.com/32369330/55266298-49c1b580-524a-11e9-8bba-0405659a16c7.gif)

Video: https://drive.google.com/file/d/10dnwLMrk5RU7GajQb1swioK1d3W04aR_/view?usp=sharing

**Comment by MasterOfTheTiger** [comment]
Sounds okay. As long as it works well that is. I do not want to make an iOS application in the Apple App Store though (since Heb12 is free software anyone could make a fork and put it on) because of their [outrageous SDK requirements](https://www.eff.org/deeplinks/2014/12/sorry-iphone-users-apples-dev-agreement-means-no-eff-mobile-app-iphone) and that it requires DRM. All of which are against the goals of Heb12 being a fully free application for reading the Bible.

**Comment by petabyt** [comment]
Most of the people I know use iPhones, so I wanted to have a way for them to use it.

**Comment by MasterOfTheTiger** [comment]
Okay. This isn't important to keep open right now. So let's close it.
